This code segment is to plot the sub problem level gradients after each BCD iteration.

In [ ]:
# Create a 2x3 grid of subplots
fig, axs = plt.subplots(2, 3, figsize=(15, 10))

# Plot data in each subplot
axs[0, 0].plot(range(1, len(gradient_values_SGD) + 1), gradient_values_SGD[:, 0, 0], label='SGD',marker = 'o')
axs[0, 0].set_title('Factor 1 1')
axs[0, 0].set_yscale('log')

axs[0, 1].plot(range(1, len(gradient_values_SGD) + 1), gradient_values_SGD[:, 0, 1], label='SGD',marker = 'o')
axs[0, 1].set_title('Factor 1 2')
axs[0, 1].set_yscale('log')

axs[0, 2].plot(range(1, len(gradient_values_SGD) + 1), gradient_values_SGD[:, 1, 0], label='SGD',marker = 'o')
axs[0, 2].set_title('Factor 2 1')
axs[0, 2].set_yscale('log')

axs[1, 0].plot(range(1, len(gradient_values_SGD) + 1), gradient_values_SGD[:, 1,1 ], label='SGD',marker = 'o')
axs[1, 0].set_title('Factor 2 2')
axs[1, 0].set_yscale('log')

axs[1, 1].plot(range(1, len(gradient_values_SGD) + 1), gradient_values_SGD[:, 0,2 ], label='SGD',marker = 'o')
axs[1, 1].set_title('Core')
axs[1, 1].set_yscale('log')


# Hide the empty subplot
axs[1, 2].axis('off')


# Add some spacing between subplots
plt.tight_layout()

# Show the plot
plt.show()


### Epoch LEvel Gradients

In [ ]:
#Factor Matrices 

for s in range(separation_rank):
        for k in range(mode):
                # Number of iterations
                max_iter = sgd_epoch_level_gradients.shape[0]

                # Define the number of rows and columns for the subplots
                rows = 5
                columns = int(np.ceil(max_iter / rows))

                # Create a figure and a set of subplots
                fig, axes = plt.subplots(rows, columns, figsize=(15, 20))

                # Flatten the axes array for easy iteration
                axes = axes.flatten()

                # Loop through each combination of the 2nd and 3rd dimensions
                for i in range(max_iter):
                    ax = axes[i]  # Get the appropriate subplot
                    
                    # Extract the data for the current subplot
                    plot_data = sgd_epoch_level_gradients[i, s, k, :]
                    
                    # Plot the data
                    ax.plot(range(1, len(plot_data) + 1), plot_data, marker='o')
                    
                    # Set the title for each subplot
                    ax.set_title(f'Gradient variation within Subproblem Iteration {i+1},{s},{k}')
                    
                    # Set the labels
                    ax.set_xlabel('Epochs')
                    ax.set_ylabel('Gradient')
                    ax.set_yscale('log')

                # Hide any unused subplots
                for j in range(max_iter, len(axes)):
                    fig.delaxes(axes[j])

                # Adjust layout to prevent overlap
                plt.tight_layout()

                # Show the plot
                plt.show()

#core tensor 

# Number of iterations
max_iter = sgd_epoch_level_gradients.shape[0]

# Define the number of rows and columns for the subplots
rows = 5
columns = int(np.ceil(max_iter / rows))

# Create a figure and a set of subplots
fig, axes = plt.subplots(rows, columns, figsize=(15, 20))

# Flatten the axes array for easy iteration
axes = axes.flatten()

# Loop through each combination of the 2nd and 3rd dimensions
for i in range(max_iter):
    ax = axes[i]  # Get the appropriate subplot
    
    # Extract the data for the current subplot
    plot_data = sgd_epoch_level_gradients[i, 0, 2, :]
    
    # Plot the data
    ax.plot(range(1, len(plot_data) + 1), plot_data, marker='o')
    
    # Set the title for each subplot
    ax.set_title(f'Gradient variation within Subproblem Iteration {i+1}, Core')
    
    # Set the labels
    ax.set_xlabel('Epochs')
    ax.set_ylabel('Gradient')
    ax.set_yscale('log')

# Hide any unused subplots
for j in range(max_iter, len(axes)):
    fig.delaxes(axes[j])

# Adjust layout to prevent overlap
plt.tight_layout()

# Show the plot
plt.show()





### Loading check points


In [ ]:
#Loading the checkpoints

import pickle
pkl_file = "/Users/lakrama/Neuro Project Codes/LSR-Tensor-Ridge-Regression/Platforms for Experments/Data/SGD_ExecutionTime_intercept_5_2024-05-30 20:10:38, n_train_650,n_test_100, tensor_dimensions:[32 32], tensor_mode_= ranks:[4 4], separation_rank:2, max_iter=15.pkl"
file= open(pkl_file, 'rb')
checkpoint_data = pickle.load(file)
file.close()

lsr_tesnsor_SGD = checkpoint_data[0]
objective_function_values_SGD__loaded = checkpoint_data[11]
print(objective_function_values_SGD_1.shape)

### Some Unit Tests


In [7]:
import numpy as np

A = np.array([[1,2,3],[2,3,4],[5,6,7]])
print(A)
A = A.flatten(order = 'F')
print(A)
print(A.shape)
A = A.reshape(1,-1)
print(A)
print(A.shape)


[[1 2 3]
 [2 3 4]
 [5 6 7]]
[1 2 5 2 3 6 3 4 7]
(9,)
[[1 2 5 2 3 6 3 4 7]]
(1, 9)
