In [4]:
# This contain all the helper function to impose the adhoc symmetricity constraint on the factor matrices and the core tensor 

def  impose_symmetry(core_tensor,factor_matrices):
    
    #making the factor matrices equal for one separation rank
    updated_factor_matrix = []
    for sep in range (len(factor_matrices)):
          updated_factor_matrix.append((factor_matrices[sep][0] + factor_matrices[sep][1] )/ 2)
          
    #projecting the core tensor in to the space of symmetric matrices
    updated_core_tensor = (core_tensor + core_tensor.T) / 2    
    
    return updated_core_tensor,updated_factor_matrix
                  

In [5]:
import numpy as np

# Unit Test 
B11 = np.array([[1,2],[5,6],[3,2]])
B21 = np.array([[2,3],[3,2],[2,4]])
B12 = np.array([[3,2],[6,6],[3,2]])
B22 = np.array([[4,3],[3,6],[7,4]])

factor_matrices_sep_1 = [B11,B21]
factor_matrices_sep_2 = [B12,B22]

factor_matrices = []
factor_matrices.append(factor_matrices_sep_1)
factor_matrices.append(factor_matrices_sep_2)

core_tensor = np.array([[2,6],[7,8]])

core_tensor_updated,factor_matrices_updated = impose_symmetry(core_tensor,factor_matrices)



In [6]:
print(factor_matrices_updated[0])
print(factor_matrices_updated[1])
print(core_tensor_updated)

[[1.5 2.5]
 [4.  4. ]
 [2.5 3. ]]
[[3.5 2.5]
 [4.5 6. ]
 [5.  3. ]]
[[2.  6.5]
 [6.5 8. ]]


In [10]:
for s in range(len(factor_matrices_updated)):
    B =+ factor_matrices_updated[s]@core_tensor_updated@(factor_matrices_updated[s]).T
    
print(B)

[[188.25  361.125 244.5  ]
 [361.125 679.5   471.75 ]
 [244.5   471.75  317.   ]]
